ALTER TABLE leads ADD COLUMN IF NOT EXISTS euid BIGINT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS country_code VARCHAR(20);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(40);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS alternate_email VARCHAR(190);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS occupation VARCHAR(200);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_name VARCHAR(200);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_type VARCHAR(160);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS follow_up_date TIMESTAMP;

UPDATE leads
SET euid = sub.rn
FROM (
  SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
  FROM leads
) sub
WHERE leads.id = sub.id AND leads.euid IS NULL;

ALTER TABLE leads ALTER COLUMN euid SET NOT NULL;
