ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS boq_amount NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS boq_file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS boq_file_path VARCHAR(500),
    ADD COLUMN IF NOT EXISTS boq_file_type VARCHAR(120),
    ADD COLUMN IF NOT EXISTS boq_file_size BIGINT;
