export const LEAD_FLOW_STATUSES = [
  "New Lead",
  "Deal",
  "Attempted",
  "Interested",
  "Design",
  "Payment",
  "Allocate",
  "Production",
  "Stock Requested",
  "Accounts",
  "Accounts Review",
  "Approval",
  "Purchase",
  "Stock Updated",
  "Production Resume",
];
